apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
spec:
  secretName: $CI_ENVIRONMENT_SLUG
  dnsNames:
  - "$CI_ENVIRONMENT_HOSTNAME"
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - "$CI_ENVIRONMENT_HOSTNAME"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer